/** Menlo's public front door; protocol and canonical Registry identities stay unchanged. */
export function menloHome(apps: string, activity: string, status: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Menlo — Permissionless iOS app distribution</title>
<meta name="description" content="Your app. In someone else’s hands. A permissionless network for iOS app makers. Share source, build on your Mac, and sign for your own iPhone.">
<meta name="theme-color" content="#f6f3ea"><meta property="og:title" content="Menlo — Your app. In someone else’s hands."><meta property="og:description" content="Permissionless iOS app distribution. Share source. Build and sign on your own Mac."><meta property="og:image" content="https://tohseno.com/menlo/hero-sharing.png?v=1">
<link rel="canonical" href="https://tohseno.com/"><link rel="icon" href="/menlo/favicon.svg?v=1" type="image/svg+xml">
<link rel="preload" href="/menlo/hero-sharing.png?v=1" as="image"><link rel="stylesheet" href="/menlo/tokens.css?v=1"><link rel="stylesheet" href="/menlo/home.css?v=1">
<script src="/menlo/home.js?v=1" defer></script></head>
<body class="menlo-landing"><a class="ml-skip" href="#main">Skip to content</a>
<header class="ml-container ml-header"><a class="ml-wordmark" href="/" aria-label="Menlo home"><img src="/menlo/menlo-mark.svg?v=1" width="40" height="40" alt="">menlo</a><nav aria-label="Primary"><a class="ml-desktop-link" href="#how-it-works">How it works</a><a href="/registry">Explore apps</a><a class="ml-button ml-desktop-link" href="#install">Get started</a></nav></header>
<main id="main"><section class="ml-container ml-hero"><div><p class="ml-eyebrow">PERMISSIONLESS iOS APP DISTRIBUTION</p><h1 class="ml-display ml-h1">Your app.<br>In someone else’s hands.</h1><p class="ml-body">A network for iOS developers to share the apps they make. Publish your source, share a link, and let someone build it on their Mac and install it on their iPhone.</p>
<div id="install"><p class="ml-install-label">Run this on your Mac</p><div class="ml-command"><code class="ml-code" id="install-command">npm i -g tohseno</code><button id="copy-command" aria-label="Copy install command">Copy command</button></div><p id="copy-status" role="status" aria-live="polite"></p><p class="ml-small ml-muted">Menlo runs on Tohseno. The tools and commands still use that name.</p></div>
<p class="ml-small">Start on a Mac with Xcode. Build and sign with your own Apple identity.</p><div class="ml-links"><a href="/registry">Explore apps ↗</a><a href="/download/macos">Mac download &amp; release status</a></div></div>
<img class="ml-hero-art" src="/menlo/hero-sharing.png?v=1" width="1536" height="1024" alt="" fetchpriority="high"></section>
<section class="ml-container ml-section" id="how-it-works"><p class="ml-eyebrow">MAKE SOMETHING. PASS IT ON.</p><h2 class="ml-display ml-h2">From your repo to their iPhone.</h2><ol class="ml-steps"><li><span class="ml-number">01</span><h3>Publish your app</h3><p>Bring an iOS app you’re already building. Set it up with Tohseno, then approve its exact source in Menlo Companion.</p><pre class="ml-code">tohseno init\ntohseno deploy</pre></li><li><span class="ml-number">02</span><h3>Share the link</h3><p>Send your app’s page to another maker. Give them a way to explore your work and receive the app.</p></li><li><span class="ml-number">03</span><h3>Build it. Make it yours.</h3><p>They receive the app through Companion, then verify, build and sign it on their Mac for their iPhone.</p></li></ol><p class="ml-note">First-time setup includes Companion and pairing. Apple signing and device requirements still apply. <a href="/docs">Read the setup guide ↗</a></p></section>
<section class="ml-container ml-section" id="apps"><div class="ml-section-heading"><h2 class="ml-display ml-h2">Apps from the network</h2><a href="/registry">Explore all apps ↗</a></div><div class="ml-app-grid">${apps}</div><p class="ml-small ml-muted">${status}</p><details class="ml-activity"><summary>Recent network activity</summary><div class="ml-app-grid">${activity}</div></details></section>
<section class="ml-container ml-belief"><img src="/menlo/spectrum-rule.svg?v=1" width="96" height="8" alt=""><h2 class="ml-display ml-h2">Good software deserves to travel.</h2><p class="ml-body">Share what you make. Learn from what others share. A network of people who believe useful software belongs in real hands.</p><a class="ml-button" href="#install">Start sharing</a></section></main>
<footer class="ml-container ml-footer"><div><span class="ml-wordmark">menlo</span><p>A network for app makers.</p><p class="ml-small ml-muted">Menlo is powered by Tohseno.</p></div><nav aria-label="Footer"><a href="#how-it-works">How it works</a><a href="https://github.com/jpfraneto/tohseno">GitHub</a><a href="/docs">Documentation</a><a href="/privacy">Privacy</a></nav></footer></body></html>`;
}
