//! Content-blind DTOs for the Companion Relay wire contract.
//!
//! Bearer capabilities are generated by clients, sent only in authorization
//! headers, and retained only by the authorized endpoint. Creation requests
//! carry lowercase SHA-256 verifiers, never the capabilities themselves.
//!
//! Exact routes and bodies:
//!
//! - `POST /v1/companion/pairing-sessions`: [`PairingSessionCreate`] ->
//!   [`PairingSessionCreated`].
//! - `POST /v1/companion/pairing-sessions/:id/respond`: raw
//!   `application/octet-stream` -> [`PairingResponseAccepted`].
//! - `GET /v1/companion/pairing-sessions/:id`: read bearer -> pending `204`
//!   or raw `application/octet-stream`.
//! - `DELETE /v1/companion/pairing-sessions/:id`: cancel bearer -> `204`.
//! - `POST /v1/companion/mailboxes`: [`MailboxCreate`] -> [`MailboxCreated`].
//! - `POST /v1/companion/mailboxes/:id/envelopes`: write bearer and direct
//!   [`OpaqueEnvelope`] JSON -> [`EnvelopeAccepted`].
//! - `GET /v1/companion/mailboxes/:id/envelopes?cursor=N&limit=N`: read bearer
//!   -> [`MailboxPage`] or `409` [`MailboxResetRequired`].
//! - `GET /v1/companion/mailboxes/:id/live?cursor=N`: read bearer -> SSE with
//!   direct envelope JSON in `envelope` events plus `reconcile`/`revoked`.
//! - `POST /v1/companion/mailboxes/:id/ack`: ack bearer and [`MailboxAck`] ->
//!   [`MailboxAcknowledged`].
//! - `DELETE /v1/companion/mailboxes/:id`: revoke bearer ->
//!   [`MailboxRevoked`].
//! - `POST /v1/companion/push/register`: push bearer and [`PushRegister`].
//! - `DELETE /v1/companion/push/register/:device_id`: push bearer and
//!   [`PushUnregister`].

use crate::crypto::{decode_array, sha256};
use crate::envelope::OpaqueEnvelope;
use crate::{parse_timestamp, require, validate_identifier, validate_text, Result};
use serde::{Deserialize, Serialize};

pub const MAX_PAIRING_RESPONSE_BYTES: usize = 64 * 1024;
pub const MAX_PAGE_ENVELOPES: usize = 256;
pub const MAX_SAFE_RELAY_INTEGER: u64 = (1_u64 << 53) - 1;
pub const PAIRING_SESSIONS_PATH: &str = "/v1/companion/pairing-sessions";
pub const MAILBOXES_PATH: &str = "/v1/companion/mailboxes";
pub const PUSH_REGISTRATION_PATH: &str = "/v1/companion/push/register";

fn validate_schema(actual: &str, expected: &str) -> Result<()> {
    require(
        actual == expected,
        format!("unsupported relay schema {actual}"),
    )
}

fn validate_verifier(label: &str, value: &str) -> Result<()> {
    require(
        value.len() == 64
            && value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)),
        format!("{label} must be a lowercase SHA-256 verifier"),
    )
}

/// Verify and hash a 32-byte base64url bearer capability for a create DTO.
pub fn capability_verifier(capability: &str) -> Result<String> {
    let capability = validate_bearer_capability(capability)?;
    Ok(hex(&sha256(&capability)))
}

pub fn validate_bearer_capability(capability: &str) -> Result<[u8; 32]> {
    decode_array::<32>("relay bearer capability", capability)
}

pub fn validate_opaque_pairing_response(bytes: &[u8]) -> Result<()> {
    require(
        !bytes.is_empty() && bytes.len() <= MAX_PAIRING_RESPONSE_BYTES,
        "opaque pairing response must contain 1..=65536 bytes",
    )
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairingSessionCreate {
    pub schema: String,
    pub expires_at: String,
    pub read_verifier: String,
    pub cancel_verifier: String,
}

impl PairingSessionCreate {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-pairing-session-create/1")?;
        parse_timestamp(&self.expires_at)?;
        validate_verifier("pairing read verifier", &self.read_verifier)?;
        validate_verifier("pairing cancel verifier", &self.cancel_verifier)?;
        require(
            self.read_verifier != self.cancel_verifier,
            "pairing read and cancel capabilities must be distinct",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairingSessionCreated {
    pub schema: String,
    pub session_id: String,
    pub expires_at: String,
}

impl PairingSessionCreated {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-pairing-session-created/1")?;
        validate_identifier("relay pairing session ID", &self.session_id)?;
        parse_timestamp(&self.expires_at).map(|_| ())
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairingResponseAccepted {
    pub schema: String,
    pub accepted: bool,
    pub duplicate: bool,
}

impl PairingResponseAccepted {
    pub fn validate(&self) -> Result<()> {
        validate_schema(
            &self.schema,
            "tohseno.companion-pairing-response-accepted/1",
        )?;
        require(self.accepted, "relay rejected the pairing response")
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxCreate {
    pub schema: String,
    pub write_verifier: String,
    pub read_verifier: String,
    pub ack_verifier: String,
    pub revoke_verifier: String,
    pub push_verifier: String,
}

impl MailboxCreate {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-create/1")?;
        let verifiers = [
            ("mailbox write verifier", &self.write_verifier),
            ("mailbox read verifier", &self.read_verifier),
            ("mailbox acknowledgement verifier", &self.ack_verifier),
            ("mailbox revoke verifier", &self.revoke_verifier),
            ("mailbox push verifier", &self.push_verifier),
        ];
        for (label, verifier) in verifiers {
            validate_verifier(label, verifier)?;
        }
        let mut unique = [
            &self.write_verifier,
            &self.read_verifier,
            &self.ack_verifier,
            &self.revoke_verifier,
            &self.push_verifier,
        ];
        unique.sort();
        require(
            unique.windows(2).all(|pair| pair[0] != pair[1]),
            "mailbox endpoint capabilities must be distinct",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxCreated {
    pub schema: String,
    pub mailbox_id: String,
    pub created_at: String,
}

impl MailboxCreated {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-created/1")?;
        validate_identifier("relay mailbox ID", &self.mailbox_id)?;
        parse_timestamp(&self.created_at).map(|_| ())
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvelopeAccepted {
    pub schema: String,
    pub accepted: bool,
    pub duplicate: bool,
    pub cursor: u64,
}

impl EnvelopeAccepted {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-envelope-accepted/1")?;
        require(self.accepted, "relay rejected the opaque envelope")?;
        require(
            (1..=MAX_SAFE_RELAY_INTEGER).contains(&self.cursor),
            "accepted envelope cursor must be a positive cross-language safe integer",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CursorEnvelope {
    pub cursor: u64,
    pub envelope: OpaqueEnvelope,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxPage {
    pub schema: String,
    pub envelopes: Vec<CursorEnvelope>,
    pub next_cursor: u64,
    pub head_cursor: u64,
    pub has_more: bool,
}

impl MailboxPage {
    pub fn validate_routing(&self, mailbox_id: &str, after_cursor: u64) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-page/1")?;
        validate_identifier("relay mailbox ID", mailbox_id)?;
        require(
            after_cursor <= MAX_SAFE_RELAY_INTEGER
                && self.next_cursor <= MAX_SAFE_RELAY_INTEGER
                && self.head_cursor <= MAX_SAFE_RELAY_INTEGER,
            "relay mailbox cursors exceed the cross-language safe integer range",
        )?;
        require(
            self.envelopes.len() <= MAX_PAGE_ENVELOPES,
            "relay mailbox page contains too many envelopes",
        )?;
        require(
            self.next_cursor >= after_cursor && self.head_cursor >= self.next_cursor,
            "relay mailbox cursors are inconsistent",
        )?;
        let mut previous = after_cursor;
        for entry in &self.envelopes {
            require(
                entry.cursor <= MAX_SAFE_RELAY_INTEGER,
                "relay mailbox entry cursor exceeds the cross-language safe integer range",
            )?;
            require(
                entry.cursor > previous && entry.cursor <= self.head_cursor,
                "relay mailbox entry cursors are not strictly increasing",
            )?;
            require(
                entry.envelope.header.mailbox_id == mailbox_id,
                "mailbox page contains a misrouted envelope",
            )?;
            entry.envelope.validate_relay_shape()?;
            previous = entry.cursor;
        }
        if let Some(last) = self.envelopes.last() {
            require(
                self.next_cursor == last.cursor,
                "next cursor does not match the final mailbox entry",
            )?;
        } else {
            require(
                self.next_cursor == after_cursor,
                "empty mailbox page advanced its cursor",
            )?;
        }
        require(
            self.has_more == (self.next_cursor < self.head_cursor),
            "mailbox has_more does not match its cursors",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxResetRequired {
    pub schema: String,
    pub reset_required: bool,
    pub reset_before_cursor: u64,
    pub head_cursor: u64,
}

impl MailboxResetRequired {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-reset-required/1")?;
        require(
            self.reset_required,
            "mailbox reset response is inconsistent",
        )?;
        require(
            self.reset_before_cursor <= self.head_cursor,
            "mailbox reset cursor exceeds the head cursor",
        )?;
        require(
            self.head_cursor <= MAX_SAFE_RELAY_INTEGER,
            "mailbox reset cursors exceed the cross-language safe integer range",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxAck {
    pub schema: String,
    pub cursor: u64,
}

impl MailboxAck {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-ack/1")?;
        require(
            (1..=MAX_SAFE_RELAY_INTEGER).contains(&self.cursor),
            "mailbox acknowledgement cursor must be a positive cross-language safe integer",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxAcknowledged {
    pub schema: String,
    pub acknowledged_cursor: u64,
}

impl MailboxAcknowledged {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-acknowledged/1")?;
        require(
            (1..=MAX_SAFE_RELAY_INTEGER).contains(&self.acknowledged_cursor),
            "acknowledged cursor must be a positive cross-language safe integer",
        )
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MailboxRevoked {
    pub schema: String,
    pub revoked: bool,
    pub revocation_epoch: u64,
}

impl MailboxRevoked {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-mailbox-revoked/1")?;
        require(self.revoked, "mailbox revocation response is inconsistent")?;
        require(
            (1..=MAX_SAFE_RELAY_INTEGER).contains(&self.revocation_epoch),
            "mailbox revocation epoch must be a positive cross-language safe integer",
        )
    }
}

#[derive(Clone, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PushRegister {
    pub schema: String,
    pub mailbox_id: String,
    pub device_id: String,
    /// Opaque APNs token. It is secret diagnostic data and must never be logged.
    pub apns_token: String,
}

impl std::fmt::Debug for PushRegister {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PushRegister")
            .field("schema", &self.schema)
            .field("mailbox_id", &"[REDACTED]")
            .field("device_id", &"[REDACTED]")
            .field("apns_token", &"[REDACTED]")
            .finish()
    }
}

impl PushRegister {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-push-register/1")?;
        validate_identifier("push mailbox ID", &self.mailbox_id)?;
        validate_identifier("push device ID", &self.device_id)?;
        validate_text("opaque APNs token", &self.apns_token, 512)
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PushUnregister {
    pub schema: String,
    pub mailbox_id: String,
}

impl PushUnregister {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-push-unregister/1")?;
        validate_identifier("push mailbox ID", &self.mailbox_id)
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelayHealth {
    pub schema: String,
    pub service_version: String,
    pub ready: bool,
    pub push_enabled: bool,
    pub maximum_envelope_bytes: u64,
    pub retention_seconds: u64,
}

impl RelayHealth {
    pub fn validate(&self) -> Result<()> {
        validate_schema(&self.schema, "tohseno.companion-relay-health/1")?;
        validate_text("relay service version", &self.service_version, 64)?;
        require(
            self.maximum_envelope_bytes > 0 && self.retention_seconds > 0,
            "relay health limits must be positive",
        )
    }
}

fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(DIGITS[(byte >> 4) as usize] as char);
        encoded.push(DIGITS[(byte & 0x0f) as usize] as char);
    }
    encoded
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::base64url;

    fn capability(byte: u8) -> String {
        base64url(&[byte; 32])
    }

    #[test]
    fn verifier_is_lowercase_sha256_and_bearer_is_absent_from_json() {
        let read_capability = capability(1);
        let cancel_capability = capability(2);
        let request = PairingSessionCreate {
            schema: "tohseno.companion-pairing-session-create/1".into(),
            expires_at: "2026-08-15T12:02:00Z".into(),
            read_verifier: capability_verifier(&read_capability).unwrap(),
            cancel_verifier: capability_verifier(&cancel_capability).unwrap(),
        };
        request.validate().unwrap();
        let json = serde_json::to_string(&request).unwrap();
        assert!(!json.contains(&read_capability));
        assert!(!json.contains(&cancel_capability));
    }

    #[test]
    fn all_mailbox_endpoint_capabilities_must_be_distinct() {
        let verifier = capability_verifier(&capability(3)).unwrap();
        let request = MailboxCreate {
            schema: "tohseno.companion-mailbox-create/1".into(),
            write_verifier: verifier.clone(),
            read_verifier: verifier.clone(),
            ack_verifier: verifier.clone(),
            revoke_verifier: verifier.clone(),
            push_verifier: verifier,
        };
        assert!(request.validate().is_err());
    }

    #[test]
    fn raw_pairing_response_is_bounded_without_parsing() {
        validate_opaque_pairing_response(b"opaque ciphertext").unwrap();
        assert!(validate_opaque_pairing_response(&[]).is_err());
        assert!(
            validate_opaque_pairing_response(&vec![0; MAX_PAIRING_RESPONSE_BYTES + 1]).is_err()
        );
    }

    #[test]
    fn relay_cursors_reject_values_javascript_cannot_represent_exactly() {
        let accepted = EnvelopeAccepted {
            schema: "tohseno.companion-envelope-accepted/1".into(),
            accepted: true,
            duplicate: false,
            cursor: MAX_SAFE_RELAY_INTEGER + 1,
        };
        assert!(accepted.validate().is_err());
        let acknowledgement = MailboxAck {
            schema: "tohseno.companion-mailbox-ack/1".into(),
            cursor: MAX_SAFE_RELAY_INTEGER + 1,
        };
        assert!(acknowledgement.validate().is_err());
    }

    #[test]
    fn push_registration_debug_is_content_free() {
        let registration = PushRegister {
            schema: "tohseno.companion-push-register/1".into(),
            mailbox_id: "mailbox_private".into(),
            device_id: "device_private".into(),
            apns_token: "private-apns-token".into(),
        };
        let debug = format!("{registration:?}");
        assert!(!debug.contains("mailbox_private"));
        assert!(!debug.contains("device_private"));
        assert!(!debug.contains("private-apns-token"));
    }
}
