[package]
name = "tohseno"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
crossterm.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tohseno-engine = { path = "../engine" }

[dev-dependencies]
tempfile = "3.15"

[[bin]]
name = "tohseno"
path = "src/main.rs"
