#!/bin/sh
# TOHSENO managed installer. It installs only checksum-pinned release artifacts
# under ~/.tohseno and never asks for credentials.
set -eu
umask 022
original_path=${PATH:-/usr/bin:/bin}
PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH

INSTALLER_VERSION="0.3.1"
CLI_VERSION="0.3.1"
CLI_ARTIFACT="tohseno-cli-${CLI_VERSION}.tar.gz"
CLI_URL_DEFAULT="https://github.com/jpfraneto/tohseno/releases/download/cli-v${CLI_VERSION}/${CLI_ARTIFACT}"
# Generated by `bun run tohseno:release`; the published asset must match exactly.
CLI_SHA256_DEFAULT="a8cbee45aacb658083c435298c4e83be062f0daa45c73951c837bc130ef37a5e"
# SHA-256 of the authenticated root inventory embedded in the CLI archive.
CLI_TREE_SHA256_DEFAULT="8d24dfc235f5a187264297576544368f4b9937c1f59fbf69d287e1302c34ed4f"

BUN_VERSION="1.2.18"
BUN_RELEASE_BASE="https://github.com/oven-sh/bun/releases/download/bun-v${BUN_VERSION}"
CLOUDFLARED_VERSION="2026.5.2"
CLOUDFLARED_RELEASE_BASE="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}"

modify_path=1
install_cloudflared=1
dry_run=0

say() { printf '%s\n' "$*"; }
die() { printf 'tohseno installer: %s\n' "$*" >&2; exit 1; }

usage() {
  say "TOHSENO installer ${INSTALLER_VERSION}"
  say ""
  say "Usage: install.sh [--non-interactive] [--no-modify-path] [--without-cloudflared] [--dry-run]"
  say ""
  say "Installs a checksum-pinned TOHSENO source release, managed Bun runtime,"
  say "and (when missing) a checksum-pinned cloudflared binary under ~/.tohseno."
  say "No credentials are requested or collected. macOS and Linux on arm64/x86_64 are supported;"
  say "only macOS with Xcode can build and launch the current iOS platform."
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --version) say "$INSTALLER_VERSION"; exit 0 ;;
    --non-interactive|--yes) ;;
    --no-modify-path) modify_path=0 ;;
    --without-cloudflared) install_cloudflared=0 ;;
    --dry-run) dry_run=1 ;;
    *) die "unknown option: $1" ;;
  esac
  shift
done

[ -n "${HOME:-}" ] || die "HOME is required"
os="${TOHSENO_INSTALL_OS:-$(uname -s)}"
arch="${TOHSENO_INSTALL_ARCH:-$(uname -m)}"

# Cloudflare digests pin the downloaded release asset, not an extracted binary.
case "$os/$arch" in
  Darwin/arm64|Darwin/aarch64)
    platform="darwin-arm64"
    bun_asset="bun-darwin-aarch64.zip"
    bun_sha="cca9eb52762bbd81eb894fc8275bba0a0654e81aad318d19869854a30f3769a2"
    cloudflared_asset="cloudflared-darwin-arm64.tgz"
    cloudflared_sha="ba94054c9fd4297645093d59d51442e5e546d07bb0516120e694a13d5b216d38"
    cloudflared_kind="tgz"
    ;;
  Darwin/x86_64|Darwin/amd64)
    platform="darwin-amd64"
    bun_asset="bun-darwin-x64.zip"
    bun_sha="c83ea4ef2126cc942056ff1958518181a2a5b6723d6aa57c96b5d0fb34d4b7dc"
    cloudflared_asset="cloudflared-darwin-amd64.tgz"
    cloudflared_sha="7240f709506bc2c1eb9da4d89cf2555499c60280ecb854b7d80e8f17d4b7903d"
    cloudflared_kind="tgz"
    ;;
  Linux/aarch64|Linux/arm64)
    platform="linux-arm64"
    bun_asset="bun-linux-aarch64.zip"
    bun_sha="1bad1671d05ba15696315ca7248ec043d29b595ff5fb15fa86b699c2255d8bc5"
    cloudflared_asset="cloudflared-linux-arm64"
    cloudflared_sha="5a4e8ce2701105271412059f44b6a0bf1ae4542b4d98ff3180c0c019443a5815"
    cloudflared_kind="binary"
    ;;
  Linux/x86_64|Linux/amd64)
    platform="linux-amd64"
    bun_asset="bun-linux-x64.zip"
    bun_sha="90e032a982ae299c62d645dac6caaa8eb00b69092bc8501bf13a590de8d099c8"
    cloudflared_asset="cloudflared-linux-amd64"
    cloudflared_sha="5286698547f03df745adb2355f04c12dde52ef425491e81f433642d695521886"
    cloudflared_kind="binary"
    ;;
  *) die "unsupported platform $os/$arch; supported: macOS or Linux on arm64/x86_64" ;;
esac

install_root="${TOHSENO_INSTALL_HOME:-$HOME/.tohseno}"
sanitized_install_root=$(printf '%s' "$install_root" | tr -d '\r\n')
[ "$sanitized_install_root" = "$install_root" ] ||
  die "install root must not contain line breaks"
cli_url="${TOHSENO_INSTALL_CLI_URL:-$CLI_URL_DEFAULT}"
cli_sha="${TOHSENO_INSTALL_CLI_SHA256:-$CLI_SHA256_DEFAULT}"
cli_tree_sha="${TOHSENO_INSTALL_CLI_TREE_SHA256:-$CLI_TREE_SHA256_DEFAULT}"
bun_url="${TOHSENO_INSTALL_BUN_URL:-$BUN_RELEASE_BASE/$bun_asset}"
bun_sha="${TOHSENO_INSTALL_BUN_SHA256:-$bun_sha}"
cloudflared_url="${TOHSENO_INSTALL_CLOUDFLARED_URL:-$CLOUDFLARED_RELEASE_BASE/$cloudflared_asset}"
cloudflared_sha="${TOHSENO_INSTALL_CLOUDFLARED_SHA256:-$cloudflared_sha}"

case "$cli_sha" in
  [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)
    [ "${#cli_sha}" -eq 64 ] || die "CLI checksum is not a complete SHA-256 digest" ;;
  *) die "CLI release is prepared but not published; the pinned artifact checksum has not been finalized" ;;
esac
case "$cli_tree_sha" in
  [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)
    [ "${#cli_tree_sha}" -eq 64 ] || die "CLI tree checksum is not a complete SHA-256 digest" ;;
  *) die "CLI release tree checksum has not been finalized" ;;
esac

if [ "$dry_run" -eq 1 ]; then
  say "TOHSENO ${CLI_VERSION} install plan for ${platform}"
  say "  root: $install_root"
  say "  CLI: $cli_url"
  say "  Bun ${BUN_VERSION}: $bun_url"
  if [ "$install_cloudflared" -eq 1 ]; then say "  cloudflared ${CLOUDFLARED_VERSION}: $cloudflared_url"; fi
  say "No files changed."
  exit 0
fi

command -v curl >/dev/null 2>&1 || die "curl is required to download verified artifacts"
command -v tar >/dev/null 2>&1 || die "tar is required to unpack the TOHSENO release"
command -v unzip >/dev/null 2>&1 || die "unzip is required to unpack the managed Bun runtime"

if command -v shasum >/dev/null 2>&1; then
  hash_file() { shasum -a 256 "$1" | awk '{print $1}'; }
elif command -v sha256sum >/dev/null 2>&1; then
  hash_file() { sha256sum "$1" | awk '{print $1}'; }
else
  die "shasum or sha256sum is required for artifact verification"
fi

download() {
  source=$1
  destination=$2
  case "$source" in
    file://*) cp "${source#file://}" "$destination" ;;
    /*|./*|../*) cp "$source" "$destination" ;;
    https://*) curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 "$source" -o "$destination" ;;
    http://127.0.0.1:*|http://localhost:*)
      [ "${TOHSENO_INSTALL_ALLOW_HTTP:-0}" = "1" ] || die "HTTP artifact overrides require TOHSENO_INSTALL_ALLOW_HTTP=1 and localhost"
      curl --fail --silent --show-error --location "$source" -o "$destination"
      ;;
    *) die "artifact URL must use HTTPS, a local file, or an explicit localhost test override" ;;
  esac
}

verify() {
  file=$1
  expected=$2
  actual=$(hash_file "$file")
  [ "$actual" = "$expected" ] || die "checksum mismatch for $(basename "$file"): expected $expected, got $actual"
}

marker_matches() {
  marker_path=$1
  marker_expected=$2
  [ -f "$marker_path" ] &&
    [ ! -L "$marker_path" ] &&
    [ -z "$(find "$marker_path" -type f -links +1 -print -quit)" ] &&
    [ "$(wc -c < "$marker_path" | tr -d '[:space:]')" = "65" ] &&
    [ "$(sed -n '1p' "$marker_path")" = "$marker_expected" ]
}

temporary=$(mktemp -d "${TMPDIR:-/tmp}/tohseno-install.XXXXXX")
cleanup() { rm -rf "$temporary"; }
trap cleanup EXIT HUP INT TERM

verify_checksum_manifest() {
  root=$1
  manifest=$2
  if command -v shasum >/dev/null 2>&1; then
    (cd "$root" && shasum -a 256 --status --strict -c "$manifest")
  else
    (cd "$root" && sha256sum --status --strict -c "$manifest")
  fi
}

verify_cli_tree() {
  root=$1
  tree_sha=$2
  root_manifest="$root/.tohseno-install-root-v1"
  checksum_manifest="$root/.tohseno-install-checksums-v1"
  executable_manifest="$root/.tohseno-install-executables-v1"
  for manifest_path in "$root_manifest" "$checksum_manifest" "$executable_manifest"; do
    [ -f "$manifest_path" ] && [ ! -L "$manifest_path" ] || return 1
  done
  [ "$(hash_file "$root_manifest")" = "$tree_sha" ] || return 1
  verify_checksum_manifest "$root" ".tohseno-install-root-v1" || return 1
  verify_checksum_manifest "$root" ".tohseno-install-checksums-v1" || return 1

  expected_paths="$temporary/expected-cli-paths-$$"
  actual_paths="$temporary/actual-cli-paths-$$"
  actual_executables="$temporary/actual-cli-executables-$$"
  {
    cut -c 67- "$checksum_manifest" | sed 's#^#./#'
    printf '%s\n' \
      "./.tohseno-install-checksums-v1" \
      "./.tohseno-install-executables-v1" \
      "./.tohseno-install-root-v1"
  } | LC_ALL=C sort > "$expected_paths"
  (
    cd "$root"
    find . -type f ! -path './.artifact.sha256' -print | LC_ALL=C sort
  ) > "$actual_paths"
  cmp -s "$expected_paths" "$actual_paths" || return 1
  [ -z "$(find "$root" -type l -print -quit)" ] || return 1
  [ -z "$(find "$root" ! -type d ! -type f ! -type l -print -quit)" ] || return 1
  [ -z "$(find "$root" -type f -links +1 -print -quit)" ] || return 1
  [ -z "$(find "$root" \( -type f -o -type d \) \( -perm -020 -o -perm -002 \) -print -quit)" ] || return 1
  (
    cd "$root"
    find . -type f -perm -111 ! -path './.artifact.sha256' -print |
      LC_ALL=C sort
  ) > "$actual_executables"
  cmp -s "$executable_manifest" "$actual_executables" || return 1
}

if [ -e "$install_root" ] || [ -L "$install_root" ]; then
  [ -d "$install_root" ] && [ ! -L "$install_root" ] ||
    die "install root is not a real directory: $install_root"
else
  mkdir -p "$install_root"
fi
install_root=$(CDPATH= cd -- "$install_root" && pwd -P)
chmod 700 "$install_root"
for managed_directory in versions runtime tools bin; do
  managed_path="$install_root/$managed_directory"
  if [ -e "$managed_path" ] || [ -L "$managed_path" ]; then
    [ -d "$managed_path" ] && [ ! -L "$managed_path" ] ||
      die "managed install path is not a real directory: $managed_path"
  else
    mkdir "$managed_path"
  fi
  chmod 700 "$managed_path"
done

cli_destination="$install_root/versions/$CLI_VERSION"
if [ -e "$cli_destination" ] || [ -L "$cli_destination" ]; then
  [ -d "$cli_destination" ] && [ ! -L "$cli_destination" ] || die "managed CLI version is not a real directory: $cli_destination"
  marker_matches "$cli_destination/.artifact.sha256" "$cli_sha" ||
    die "existing managed CLI version has an unsafe artifact marker: $cli_destination"
  verify_cli_tree "$cli_destination" "$cli_tree_sha" ||
    die "existing managed CLI tree failed integrity verification: $cli_destination"
  say "TOHSENO ${CLI_VERSION} already verified."
else
  cli_archive="$temporary/$CLI_ARTIFACT"
  download "$cli_url" "$cli_archive"
  verify "$cli_archive" "$cli_sha"
  mkdir -p "$temporary/cli"
  tar -xzf "$cli_archive" -C "$temporary/cli"
  extracted_cli="$temporary/cli/tohseno-cli-$CLI_VERSION"
  [ -f "$extracted_cli/factory-source/packages/cli/src/bin.ts" ] || die "verified CLI artifact has an unexpected layout"
  verify_cli_tree "$extracted_cli" "$cli_tree_sha" ||
    die "verified CLI artifact failed internal tree verification"
  cli_staging="$install_root/versions/.${CLI_VERSION}.installing-$$"
  rm -rf "$cli_staging"
  mv "$extracted_cli" "$cli_staging"
  printf '%s\n' "$cli_sha" > "$cli_staging/.artifact.sha256"
  chmod 644 "$cli_staging/.artifact.sha256"
  verify_cli_tree "$cli_staging" "$cli_tree_sha" ||
    die "staged CLI tree failed integrity verification"
  mv "$cli_staging" "$cli_destination"
  say "Installed TOHSENO ${CLI_VERSION}."
fi
if [ -e "$install_root/versions/current" ] && [ ! -L "$install_root/versions/current" ]; then
  die "managed CLI current pointer is not a symlink: $install_root/versions/current"
fi
ln -sfn "$CLI_VERSION" "$install_root/versions/current"

bun_destination="$install_root/runtime/bun-$BUN_VERSION"
bun_binary_marker="$bun_destination/.binary.sha256"
if [ -e "$bun_destination" ] || [ -L "$bun_destination" ]; then
  [ -d "$bun_destination" ] && [ ! -L "$bun_destination" ] || die "managed Bun runtime is not a real directory: $bun_destination"
  marker_matches "$bun_destination/.artifact.sha256" "$bun_sha" ||
    die "existing managed Bun runtime has an unsafe artifact marker"
  [ -f "$bun_destination/bin/bun" ] &&
    [ ! -L "$bun_destination/bin/bun" ] &&
    [ -z "$(find "$bun_destination/bin/bun" -type f -links +1 -print -quit)" ] &&
    [ -x "$bun_destination/bin/bun" ] ||
    die "existing managed Bun binary is unsafe"
  if [ -e "$bun_binary_marker" ] || [ -L "$bun_binary_marker" ]; then
    [ -f "$bun_binary_marker" ] &&
      [ ! -L "$bun_binary_marker" ] &&
      [ -z "$(find "$bun_binary_marker" -type f -links +1 -print -quit)" ] ||
      die "managed Bun binary checksum marker is unsafe"
  else
    bun_archive="$temporary/$bun_asset"
    download "$bun_url" "$bun_archive"
    verify "$bun_archive" "$bun_sha"
    mkdir -p "$temporary/bun-migration"
    unzip -q "$bun_archive" -d "$temporary/bun-migration"
    bun_reference=$(find "$temporary/bun-migration" -type f -name bun -print | head -n 1)
    [ -n "$bun_reference" ] || die "verified Bun artifact has an unexpected layout"
    bun_binary_digest=$(hash_file "$bun_reference")
    [ "$(hash_file "$bun_destination/bin/bun")" = "$bun_binary_digest" ] ||
      die "existing managed Bun binary differs from its verified release"
    printf '%s\n' "$bun_binary_digest" > "$bun_binary_marker"
    chmod 644 "$bun_binary_marker"
  fi
  if [ -f "$bun_binary_marker" ]; then
    bun_binary_digest=$(sed -n '1p' "$bun_binary_marker")
    case "$bun_binary_digest" in
      [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)
        [ "${#bun_binary_digest}" -eq 64 ] ||
          die "managed Bun binary checksum is incomplete" ;;
      *) die "managed Bun binary checksum is invalid" ;;
    esac
    marker_matches "$bun_binary_marker" "$bun_binary_digest" ||
      die "managed Bun binary checksum marker is not canonical"
    [ "$(hash_file "$bun_destination/bin/bun")" = "$bun_binary_digest" ] ||
      die "existing managed Bun binary failed integrity verification"
  fi
  say "Managed Bun ${BUN_VERSION} already verified."
else
  bun_archive="$temporary/$bun_asset"
  download "$bun_url" "$bun_archive"
  verify "$bun_archive" "$bun_sha"
  mkdir -p "$temporary/bun"
  unzip -q "$bun_archive" -d "$temporary/bun"
  bun_binary=$(find "$temporary/bun" -type f -name bun -print | head -n 1)
  [ -n "$bun_binary" ] || die "verified Bun artifact has an unexpected layout"
  bun_staging="$install_root/runtime/.bun-$BUN_VERSION.installing-$$"
  rm -rf "$bun_staging"
  mkdir -p "$bun_staging/bin"
  cp "$bun_binary" "$bun_staging/bin/bun"
  chmod 755 "$bun_staging/bin/bun"
  bun_binary_digest=$(hash_file "$bun_staging/bin/bun")
  printf '%s\n' "$bun_sha" > "$bun_staging/.artifact.sha256"
  printf '%s\n' "$bun_binary_digest" > "$bun_staging/.binary.sha256"
  chmod 644 "$bun_staging/.artifact.sha256" "$bun_staging/.binary.sha256"
  mv "$bun_staging" "$bun_destination"
  say "Installed managed Bun ${BUN_VERSION}."
fi
if [ -e "$install_root/runtime/current" ] && [ ! -L "$install_root/runtime/current" ]; then
  die "managed Bun current pointer is not a symlink: $install_root/runtime/current"
fi
ln -sfn "bun-$BUN_VERSION" "$install_root/runtime/current"

managed_cloudflared_digest=""
if [ "$install_cloudflared" -eq 1 ]; then
  existing_cloudflared=$(command -v cloudflared 2>/dev/null || true)
  if [ "$existing_cloudflared" = "$install_root/bin/cloudflared" ]; then
    existing_cloudflared=""
  fi
  if [ -n "$existing_cloudflared" ]; then
    say "Using existing cloudflared at $existing_cloudflared."
  else
    cloudflared_destination="$install_root/tools/cloudflared-$CLOUDFLARED_VERSION"
    cloudflared_marker="$cloudflared_destination.sha256"
    cloudflared_binary_marker="$cloudflared_destination.binary.sha256"
    if [ -e "$cloudflared_destination" ] || [ -L "$cloudflared_destination" ]; then
      [ -f "$cloudflared_destination" ] && [ ! -L "$cloudflared_destination" ] || die "managed cloudflared is not a regular file"
      marker_matches "$cloudflared_marker" "$cloudflared_sha" ||
        die "existing managed cloudflared has an unsafe artifact marker"
      if [ -e "$cloudflared_binary_marker" ] || [ -L "$cloudflared_binary_marker" ]; then
        [ -f "$cloudflared_binary_marker" ] &&
          [ ! -L "$cloudflared_binary_marker" ] &&
          [ -z "$(find "$cloudflared_binary_marker" -type f -links +1 -print -quit)" ] ||
          die "managed cloudflared binary checksum marker is unsafe"
      else
        cloudflared_download="$temporary/$cloudflared_asset"
        download "$cloudflared_url" "$cloudflared_download"
        verify "$cloudflared_download" "$cloudflared_sha"
        if [ "$cloudflared_kind" = "tgz" ]; then
          mkdir -p "$temporary/cloudflared-migration"
          tar -xzf "$cloudflared_download" -C "$temporary/cloudflared-migration"
          cloudflared_reference=$(find "$temporary/cloudflared-migration" -type f -name cloudflared -print | head -n 1)
          [ -n "$cloudflared_reference" ] ||
            die "verified cloudflared artifact has an unexpected layout"
        else
          cloudflared_reference="$cloudflared_download"
        fi
        managed_cloudflared_digest=$(hash_file "$cloudflared_reference")
        [ "$(hash_file "$cloudflared_destination")" = "$managed_cloudflared_digest" ] ||
          die "existing managed cloudflared differs from its verified release"
        printf '%s\n' "$managed_cloudflared_digest" > "$cloudflared_binary_marker"
        chmod 644 "$cloudflared_binary_marker"
      fi
      managed_cloudflared_digest=$(sed -n '1p' "$cloudflared_binary_marker")
      case "$managed_cloudflared_digest" in
        [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)
          [ "${#managed_cloudflared_digest}" -eq 64 ] ||
            die "managed cloudflared binary checksum is incomplete" ;;
        *) die "managed cloudflared binary checksum is invalid" ;;
      esac
      marker_matches "$cloudflared_binary_marker" "$managed_cloudflared_digest" ||
        die "managed cloudflared binary checksum marker is not canonical"
      [ "$(hash_file "$cloudflared_destination")" = "$managed_cloudflared_digest" ] ||
        die "existing managed cloudflared binary failed integrity verification"
      say "Managed cloudflared ${CLOUDFLARED_VERSION} already verified."
    else
      cloudflared_download="$temporary/$cloudflared_asset"
      download "$cloudflared_url" "$cloudflared_download"
      verify "$cloudflared_download" "$cloudflared_sha"
      if [ "$cloudflared_kind" = "tgz" ]; then
        mkdir -p "$temporary/cloudflared"
        tar -xzf "$cloudflared_download" -C "$temporary/cloudflared"
        cloudflared_binary=$(find "$temporary/cloudflared" -type f -name cloudflared -print | head -n 1)
        [ -n "$cloudflared_binary" ] || die "verified cloudflared artifact has an unexpected layout"
      else
        cloudflared_binary="$cloudflared_download"
      fi
      cloudflared_staging="$install_root/tools/.cloudflared-$CLOUDFLARED_VERSION.installing-$$"
      cp "$cloudflared_binary" "$cloudflared_staging"
      chmod 755 "$cloudflared_staging"
      managed_cloudflared_digest=$(hash_file "$cloudflared_staging")
      mv "$cloudflared_staging" "$cloudflared_destination"
      printf '%s\n' "$cloudflared_sha" > "$cloudflared_marker"
      printf '%s\n' "$managed_cloudflared_digest" > "$cloudflared_binary_marker"
      chmod 644 "$cloudflared_marker" "$cloudflared_binary_marker"
      say "Installed managed cloudflared ${CLOUDFLARED_VERSION}."
    fi
    if [ -e "$install_root/bin/cloudflared" ] &&
      [ ! -L "$install_root/bin/cloudflared" ]; then
      die "managed cloudflared pointer is not a symlink"
    fi
    ln -sfn "../tools/cloudflared-$CLOUDFLARED_VERSION" "$install_root/bin/cloudflared"
  fi
fi

if [ -e "$install_root/bin/cloudflared" ] ||
  [ -L "$install_root/bin/cloudflared" ]; then
  [ -L "$install_root/bin/cloudflared" ] &&
    [ "$(readlink "$install_root/bin/cloudflared")" = "../tools/cloudflared-$CLOUDFLARED_VERSION" ] ||
    die "managed cloudflared pointer is unsafe"
  cloudflared_destination="$install_root/tools/cloudflared-$CLOUDFLARED_VERSION"
  cloudflared_binary_marker="$cloudflared_destination.binary.sha256"
  [ -f "$cloudflared_destination" ] &&
    [ ! -L "$cloudflared_destination" ] &&
    [ -z "$(find "$cloudflared_destination" -type f -links +1 -print -quit)" ] &&
    [ -x "$cloudflared_destination" ] ||
    die "managed cloudflared binary is unsafe"
  [ -f "$cloudflared_binary_marker" ] &&
    [ ! -L "$cloudflared_binary_marker" ] &&
    [ -z "$(find "$cloudflared_binary_marker" -type f -links +1 -print -quit)" ] ||
    die "managed cloudflared binary checksum marker is unsafe"
  managed_cloudflared_digest=$(sed -n '1p' "$cloudflared_binary_marker")
  case "$managed_cloudflared_digest" in
    [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*)
      [ "${#managed_cloudflared_digest}" -eq 64 ] ||
        die "managed cloudflared binary checksum is incomplete" ;;
    *) die "managed cloudflared binary checksum is invalid" ;;
  esac
  marker_matches "$cloudflared_binary_marker" "$managed_cloudflared_digest" ||
    die "managed cloudflared binary checksum marker is not canonical"
  [ "$(hash_file "$cloudflared_destination")" = "$managed_cloudflared_digest" ] ||
    die "managed cloudflared binary failed integrity verification"
fi

wrapper="$install_root/bin/tohseno"
if [ -e "$wrapper" ] || [ -L "$wrapper" ]; then
  [ -f "$wrapper" ] && [ ! -L "$wrapper" ] ||
    die "managed TOHSENO wrapper is not a regular file: $wrapper"
fi
wrapper_staging="$temporary/tohseno-wrapper"
{
  printf '%s\n' \
    '#!/bin/sh' \
    'set -eu' \
    "CLI_VERSION='$CLI_VERSION'" \
    "CLI_SHA256='$cli_sha'" \
    "CLI_TREE_SHA256='$cli_tree_sha'" \
    "BUN_VERSION='$BUN_VERSION'" \
    "BUN_SHA256='$bun_sha'" \
    "BUN_BINARY_SHA256='$bun_binary_digest'" \
    "CLOUDFLARED_VERSION='$CLOUDFLARED_VERSION'" \
    "MANAGED_CLOUDFLARED_SHA256='$managed_cloudflared_digest'"
  cat <<'WRAPPER'
original_path=${PATH:-/usr/bin:/bin}
PATH=/usr/bin:/bin:/usr/sbin:/sbin
export PATH
integrity_die() {
  printf 'tohseno: managed installation failed integrity verification: %s\n' "$*" >&2
  exit 1
}
if command -v shasum >/dev/null 2>&1; then
  hash_file() { shasum -a 256 "$1" | awk '{print $1}'; }
elif command -v sha256sum >/dev/null 2>&1; then
  hash_file() { sha256sum "$1" | awk '{print $1}'; }
else
  integrity_die "shasum or sha256sum is required"
fi
marker_matches() {
  marker_path=$1
  marker_expected=$2
  [ -f "$marker_path" ] &&
    [ ! -L "$marker_path" ] &&
    [ -z "$(find "$marker_path" -type f -links +1 -print -quit)" ] &&
    [ "$(wc -c < "$marker_path" | tr -d '[:space:]')" = "65" ] &&
    [ "$(sed -n '1p' "$marker_path")" = "$marker_expected" ]
}
verify_checksum_manifest() {
  verify_root=$1
  verify_manifest=$2
  if command -v shasum >/dev/null 2>&1; then
    (cd "$verify_root" && shasum -a 256 --status --strict -c "$verify_manifest")
  else
    (cd "$verify_root" && sha256sum --status --strict -c "$verify_manifest")
  fi
}
verify_cli_tree() {
  verify_root=$1
  verify_tree_sha=$2
  verify_root_manifest="$verify_root/.tohseno-install-root-v1"
  verify_checksum_manifest_path="$verify_root/.tohseno-install-checksums-v1"
  verify_executable_manifest="$verify_root/.tohseno-install-executables-v1"
  for verify_manifest_path in \
    "$verify_root_manifest" \
    "$verify_checksum_manifest_path" \
    "$verify_executable_manifest"; do
    [ -f "$verify_manifest_path" ] && [ ! -L "$verify_manifest_path" ] ||
      return 1
  done
  [ "$(hash_file "$verify_root_manifest")" = "$verify_tree_sha" ] || return 1
  verify_checksum_manifest "$verify_root" ".tohseno-install-root-v1" ||
    return 1
  verify_checksum_manifest "$verify_root" ".tohseno-install-checksums-v1" ||
    return 1
  {
    cut -c 67- "$verify_checksum_manifest_path" | sed 's#^#./#'
    printf '%s\n' \
      "./.tohseno-install-checksums-v1" \
      "./.tohseno-install-executables-v1" \
      "./.tohseno-install-root-v1"
  } | LC_ALL=C sort > "$integrity_temp/expected"
  (
    cd "$verify_root"
    find . -type f ! -path './.artifact.sha256' -print | LC_ALL=C sort
  ) > "$integrity_temp/actual"
  cmp -s "$integrity_temp/expected" "$integrity_temp/actual" || return 1
  [ -z "$(find "$verify_root" -type l -print -quit)" ] || return 1
  [ -z "$(find "$verify_root" ! -type d ! -type f ! -type l -print -quit)" ] ||
    return 1
  [ -z "$(find "$verify_root" -type f -links +1 -print -quit)" ] || return 1
  [ -z "$(find "$verify_root" \( -type f -o -type d \) \( -perm -020 -o -perm -002 \) -print -quit)" ] ||
    return 1
  (
    cd "$verify_root"
    find . -type f -perm -111 ! -path './.artifact.sha256' -print |
      LC_ALL=C sort
  ) > "$integrity_temp/executables"
  cmp -s "$verify_executable_manifest" "$integrity_temp/executables" ||
    return 1
}

bin_directory=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
managed_home=$(dirname "$bin_directory")
cli_root="$managed_home/versions/$CLI_VERSION"
bun_root="$managed_home/runtime/bun-$BUN_VERSION"
integrity_temp=$(mktemp -d "${TMPDIR:-/tmp}/tohseno-integrity.XXXXXX") ||
  integrity_die "cannot create a private temporary directory"
cleanup_integrity() { rm -rf "$integrity_temp"; }
trap cleanup_integrity EXIT HUP INT TERM

[ -d "$cli_root" ] && [ ! -L "$cli_root" ] ||
  integrity_die "CLI version directory is unsafe"
marker_matches "$cli_root/.artifact.sha256" "$CLI_SHA256" ||
  integrity_die "CLI artifact marker differs"
verify_cli_tree "$cli_root" "$CLI_TREE_SHA256" ||
  integrity_die "CLI tree differs"

[ -d "$bun_root" ] && [ ! -L "$bun_root" ] ||
  integrity_die "Bun version directory is unsafe"
marker_matches "$bun_root/.artifact.sha256" "$BUN_SHA256" ||
  integrity_die "Bun artifact marker differs"
marker_matches "$bun_root/.binary.sha256" "$BUN_BINARY_SHA256" ||
  integrity_die "Bun binary marker differs"
[ -f "$bun_root/bin/bun" ] &&
  [ ! -L "$bun_root/bin/bun" ] &&
  [ -z "$(find "$bun_root/bin/bun" -type f -links +1 -print -quit)" ] &&
  [ -x "$bun_root/bin/bun" ] &&
  [ "$(hash_file "$bun_root/bin/bun")" = "$BUN_BINARY_SHA256" ] ||
  integrity_die "Bun binary differs"

if [ -n "$MANAGED_CLOUDFLARED_SHA256" ]; then
  cloudflared_binary="$managed_home/tools/cloudflared-$CLOUDFLARED_VERSION"
  cloudflared_link="$managed_home/bin/cloudflared"
  [ -L "$cloudflared_link" ] &&
    [ "$(readlink "$cloudflared_link")" = "../tools/cloudflared-$CLOUDFLARED_VERSION" ] ||
    integrity_die "cloudflared pointer differs"
  [ -f "$cloudflared_binary" ] &&
    [ ! -L "$cloudflared_binary" ] &&
    [ -z "$(find "$cloudflared_binary" -type f -links +1 -print -quit)" ] &&
    [ -x "$cloudflared_binary" ] &&
    [ "$(hash_file "$cloudflared_binary")" = "$MANAGED_CLOUDFLARED_SHA256" ] ||
    integrity_die "cloudflared binary differs"
fi

: "${TOHSENO_HOME:=$managed_home}"
TOHSENO_BUN="$bun_root/bin/bun"
TOHSENO_SOURCE_ROOT="$cli_root/factory-source"
PATH="$managed_home/bin:$original_path"
export PATH TOHSENO_HOME TOHSENO_BUN TOHSENO_SOURCE_ROOT
trap - EXIT HUP INT TERM
rm -rf "$integrity_temp"
exec "$TOHSENO_BUN" "$TOHSENO_SOURCE_ROOT/packages/cli/src/bin.ts" "$@"
WRAPPER
} > "$wrapper_staging"
chmod 755 "$wrapper_staging"
mv -f "$wrapper_staging" "$wrapper"

installed_version=$("$wrapper" --version) || die "installed TOHSENO executable did not start"
[ "$installed_version" = "$CLI_VERSION" ] || die "installed executable reported unexpected version $installed_version"

PATH=$original_path
export PATH
path_note=""
case ":${PATH:-}:" in
  *":$install_root/bin:"*) ;;
  *)
    if [ "$modify_path" -eq 1 ]; then
      shell_name=$(basename "${SHELL:-sh}")
      case "$shell_name" in
        zsh) shell_file="$HOME/.zshrc" ;;
        bash) shell_file="$HOME/.bashrc" ;;
        *) shell_file="$HOME/.profile" ;;
      esac
      marker="# >>> tohseno managed path >>>"
      shell_file_safe=1
      sanitized_shell_file=$(printf '%s' "$shell_file" | tr -d '\r\n')
      sanitized_install_root=$(printf '%s' "$install_root" | tr -d '\r\n')
      if [ "$sanitized_shell_file" != "$shell_file" ] ||
        [ "$sanitized_install_root" != "$install_root" ]; then
        shell_file_safe=0
      elif [ -e "$shell_file" ] || [ -L "$shell_file" ]; then
        if [ ! -f "$shell_file" ] ||
          [ -L "$shell_file" ] ||
          [ -n "$(find "$shell_file" -type f -links +1 -print -quit)" ]; then
          shell_file_safe=0
        fi
      fi
      escaped_install_bin=$(printf '%s' "$install_root/bin" |
        sed "s/'/'\\\\''/g")
      if [ "$shell_file_safe" -eq 1 ]; then
        if ! grep -F "$marker" "$shell_file" >/dev/null 2>&1; then
          {
            printf '\n%s\n' "$marker"
            printf "export PATH='%s':\"\$PATH\"\n" "$escaped_install_bin"
            printf '%s\n' "# <<< tohseno managed path <<<"
          } >> "$shell_file"
        fi
      else
        say "Skipped shell profile update because the target is not a safe regular file."
      fi
      path_note="Restart your shell, or run: export PATH='$escaped_install_bin':\"\$PATH\""
    else
      escaped_install_bin=$(printf '%s' "$install_root/bin" |
        sed "s/'/'\\\\''/g")
      path_note="Add TOHSENO to this shell: export PATH='$escaped_install_bin':\"\$PATH\""
    fi
    ;;
esac

say ""
say "TOHSENO ${CLI_VERSION} is installed at $wrapper"
[ -z "$path_note" ] || say "$path_note"
if command -v git >/dev/null 2>&1; then say "Git: found"; else say "Git: missing (required to create shots)"; fi
if command -v xcodebuild >/dev/null 2>&1; then say "Xcode: found"; else say "Xcode: missing (shots can be created; iOS cannot launch here)"; fi
if command -v codex >/dev/null 2>&1; then say "Codex: found"; else say "Codex: not found"; fi
if command -v claude >/dev/null 2>&1; then say "Claude Code: found"; else say "Claude Code: not found"; fi
if command -v cloudflared >/dev/null 2>&1 || [ -x "$install_root/bin/cloudflared" ]; then say "cloudflared: found"; else say "cloudflared: not installed (Quick Tunnels unavailable)"; fi
say ""
say "Next: tohseno"
